language: ruby
rvm:
  - '2.1.2'
  - '2.1.1'
  - '2.1.0'
  - '2.0.0'
  - '1.9.3'
addons:
  postgresql: '9.3'
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script: 'cd spec/dummy/ && bundle exec rspec spec'
